### ISSUE TITLE
custom variables

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#112]
This is for a new `custom_statistics` section.
Similar flow to the variable_display section

## Endpoints

Questions: Does a custom variable need a numeric "id" or does a unique name suffice?  Where would the numeric be generated?

- [x] add a custom variable
   - updates preprocess file
- [x] update a custom variable
- [x] delete a custom variable

**Comment by raprasad** [comment]
from @Shoeboxam 

The custom stats are described here:
https://github.com/TwoRavens/metadata#adding-fields-to-preprocess

I implemented UI for it that reads/writes to local javascript variables. The way they're implemented through the API is completely undefined. They could go into the preprocess.json, or be their own endpoint- and I'm happy to work with either.

Here's my recommendation:

```json
[
 {
   "id": 1,
   "name": "Third order statistic",
   "variables": ["lpop"], _optional_
   "image": "image_id", _optional_
   "value": "23.45",
   "description": "Third smallest value",
   "replication": "sorted(X)[2]",
   "omit": false _optional_
 },
 {*custom statistic 2*},
 ...
]
```
This could be incorporated into the preprocess.json as a root level key
"custom": [{*custom statistic 1*}, {*custom statistic 2*}, ...]
I think this will cover all the specs in that readme.

Perhaps we have endpoints for
1. downloading an image given an image_id
2. setting a custom metadata field. If no id is given, creates a new field and returns the id. If id is given, then edit that field with the whatever values are passed. possibly handle image uploads here too, tied to a custom field

**Comment by raprasad** [comment]
- reference: MetadataUpdateUtil

**Comment by kripanshu** [comment]
The whole flow is similar to variable_display section. 
1. **Add custom variable**: The JSON expected from the editor( front-end) would be similar to this:
``` 
[
 {
   "id": 1,
   "name": "Third order statistic",
   "variables": ["lpop"], _optional_
   "image": "image_id", _optional_
   "value": "23.45",
   "description": "Third smallest value",
   "replication": "sorted(X)[2]",
   "omit": false _optional_
 },
 {*custom statistic 2*},
 ...
]
```
@Shoeboxam :
In this JSON response,
Id: alphanumeric?
image: how would you be returning the image?
omit: how exactly omit works here?

**Comment by kripanshu** [comment]
**2. Update custom variable:**
JSON would be similar to this:
``` 
[
   {
      "id":1,
      "updates":{
         "name":"Fourth order statistic",
         "value":40
      }
   }
]
```
Update would be done for the custom statistics with ID:1 and the inside given fields would be updated.

**Comment by Shoeboxam** [comment]
About handling an image, the preprocess.json has an optional key “image” that, when set, provides an image ID.

To retrieve the image, use the image ID with a separate endpoint that returns the image. The image ID can be a string or int, doesn’t matter. I really just want to keep images out of the preprocess.json request to keep it light.

My initial thinking was, if the variables key is empty or missing, then it is a dataset-level statistic. If you think this might be confusing, we could split it off into a separate root-level key.

**Comment by kripanshu** [comment]
Delete would work like update except the part that 
1. deleting the whole custom statistics:
2. deleting a field of custom statistics. e.g. value, name etc.

**Comment by kripanshu** [comment]
So if a user wants to submit a list of custom-statistics (let's say `custom-statistic_1,custom-statistic_2,custom-statistic_3,custom-statistic_4`) for a particular preprocess_id. 
1. Do you want the user to submit custom-statistics one by one? or as a single list( containing all 4 statistics e.g. mentioned above) in a go?
2. If as a list, then what should be the **response** you are accepting when any of them fails? Should message success be ` partial success` or ` fail`
  - e.g. out of the list of 4 custom-statistics, custom-statistic 3 fails. 
    The response can be : ```{
   "custom-statistics_response":{
      "message":"partial success",
      "preprocess_id":12,
      "custom-statistics":{
         "custom-statistic_1":{
            "success":"true",
            "message":"worked"
         },
         "custom-statistic_2":{
            "success":"true",
            "message":"worked"
         },
         "custom-statistic_3":{
            "success":"false",
            "message":"variable does not exist"
         },
         "custom-statistic_4":{
            "success":"true",
            "message":"worked"
         }
      }
   }
} ```

@vjdorazio @Shoeboxam

**Comment by raprasad** [comment]
possible id scheme

```python

ids = """id_000001
id_000002
id_000003
id_000005""".split()

ids.sort()
latest_id  = ids[-1]
_unused, idnum = latest_id.split('_')
next_num = str(int(idnum) + 1)
next_id = 'id_%s' % next_num.zfill(6)
```

**Comment by Shoeboxam** [comment]
From the UI perspective, I’d prefer to set these as atomically as possible. 

In other parts of the menu, updates happen as the user inputs each field or toggles visibility, so there’s no save or update buttons anywhere.

**Comment by kripanshu** [comment]
Documentation for the custom_statistics:

## ***1. Add custom_statistics*:**
- api endpoint: http://127.0.0.1:8080/preprocess/form/custom-statistics
- expected JSON from front end: 
``` 
{  
   "preprocess_id":1,
   "custom_statistics":[  
      {  
         "variables":[  
            "light"
         ],
         "image":[  

         ],
         "name":"median",
         "value":"52",
         "description":"median of numbers",
         "replication":"count/2"
      }
   ]
}
``` 
**2. Update custom_statistics ( here we only update the latest version)**:
- api endpoint : http://127.0.0.1:8080/preprocess/form/custom-statistics-update
- expected JSON from front end:
``` 
{  
   "preprocess_id":1,
   "custom_statistics":[  
      {  
         "id":"id_1",
         "updates":{  
            "name":"Fourth order statistic",
            "value":80
         }
      },
      {  
         "id":"id_2",
         "updates":{  
            "name":"third order statistic",
            "value":810,
            "description":"new desc"
         }
      }
   ]
}
```
**## 3. Delete custom_statistics ( only for latest version):**
- endpoint : http://127.0.0.1:8080/preprocess/form/custom-statistics-delete
- expected JSON: 
``` 
{  
   "preprocess_id":1,
   "custom_statistics":[  
      {  
         "id":"id_1",
         "delete":[  
            "description",
            "replication"
         ]
      },
      {  
         "id":"id_2",
         "delete":[  
            "id"
         ]
      }
   ]
}
```

@Shoeboxam Working according to the above JSON files. Let me know if you want to add something.
