### ISSUE TITLE
API endpoints: validate metadata using JSON schema

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#136]
schema_util.py
   - reusable methods after preprocess metadata created/modified, etc
      - method to validate the schema
      - method to validate the data with a schema

api endpoint:
  - send preprocess data in JSON format
  - schema version (optional, use "latest" by default"

reference:  see `run_validate.py` file

**Comment by kripanshu** [comment]
link : https://github.com/TwoRavens/raven-metadata-service/commits/Json-schema
Completed with endpoint
