### ISSUE TITLE
Preprocess: backport to old version

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#205]
## Code

- Create a python script/program to convert:
   - **From**: the current preprocess output
   - **To**:  the original preprocess file format from ~5 years ago

- Allow command line and python library options to give output in the old format

## Purpose

Allow Dataverse installations to switch from the older R script, with associated RServe/RApache setup, etc. to a python based service

## Accessing older preprocess output

The older version preprocess output is accessible on Dataverse using this url format and substituting the proper `fileId`. :
    
  ```
  https://dataverse.harvard.edu/api/access/datafile/3608609?format=prep
  ```
- Note the datafile id in the example above ,`3608609` is not readily accessible on the Dataverse pages.

One way to find it is:
1. Go to a Dataverse file page. 
    - e.g. https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/E43MOQ/7D27MY
2. Click the **Explore** button which launches a new window
3. Find the fileId in the url of the new window, e.g.:
    - https://scholarsportal.github.io/Dataverse-Data-Explorer/?fileId=3608609&siteUrl=https://dataverse.harvard.edu
    - See the **fileId** attribute in the link above

**Comment by aaron-lebo** [comment]
This is in place with the latest commit on develop. python preprocess.py accepts an --old-format argument and the underlying methods that class (like runner.get_final_json) accept a similar old_format argument.

The two versions output different values in some cases and the R version has a tendency to overconvert things to strings (numbers) so it's not an exact conversion, but it works unless an end script is looki
