### ISSUE TITLE
backend logic for processing dataverse files

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#35]
downloads/processes:
- [x] file 
    - https://dataverse.harvard.edu/api/access/datafile/{ file id }
     - python requests library: 
          - download file
          - create PreprocessJob object 
                 - `source_file` = downloaded file, see use of `ContentFile` in `class 
PreprocessResultUpdater`
- [x] metadata (json-ld)
    - add citation from the dataset id.  (how to go from data file id to doi

**Comment by raprasad** [comment]
- [ ] DataverseJobStatus -- to check if the tasks ends before a PreprocessJob is created

**Comment by raprasad** [comment]
for citation, from @pdurbin:

> Here's a hack that prints "The DOI for file id 3040230 is doi:10.7910/DVN/TJCLKP"

```
#!/bin/sh
# https://dataverse.harvard.edu/file.xhtml?fileId=3040230
FILEID=3040230
FILE_SEARCH=`curl -s https://dataverse.harvard.edu/api/search?q=entityId:$FILEID | jq .`
DOI_URL=`echo $FILE_SEARCH | jq '.data.items[0].dataset_citation' | grep -o 'https://doi.*' | cut -d, -f1`
DOI=`echo $DOI_URL | sed 's/https:\/\/doi/doi:/' | sed 's/\.org\///'`
echo "The DOI for file id $FILEID is $DOI"
```

**Comment by pdurbin** [comment]
@raprasad I'd to replace that hack with the kind of solution you're proposing in https://github.com/IQSS/dataverse/issues/4616

**Comment by raprasad** [comment]
- [ ] check for existing preprocess files
- [ ] simple web form
