### ISSUE TITLE
endpoint: update preprocess file / version orig file

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#46]
- accept JSON request
- locate existing PreprocessJob object
   - load preprocess JSON file into OrderedDict
   - update - separate class to handle updates
     - variable_display
     - variable values
     - export to JSON file
     - create PreprocessUpdate object as a "log/history"
   - Next: Create a new 

PreprocessJob - link to preprocess file
   - PreprocessUpdate - make PreprocessUpdate object
       - save update request, e.g. JSON request
       - link to the new preprocess file 
       - link to original PreprocessJob
       - link to previous PreprocessJob

**Comment by raprasad** [comment]
- original preprocess **always save full file** (PreprocessJob)
     - version 1  **save the orig change request** (PreprocessUpdate)
     - version 2  **save the orig change request**  (PreprocessUpdate)
     - version 3 **save full file of the latest?**  (PreprocessUpdate)

**Comment by raprasad** [comment]
example of an update

```json
{
"preprocess_id": 45,
"variable_updates": { 	
   "cylinders" : {
     "omit": ["mean", "median"],
     "label": "(new value is here)"
   },
   "mpg" : {
     "viewable": false
   }
}
```

**Comment by kripanshu** [comment]
How should I do this :  ``` create PreprocessUpdate object as a "log/history" ```

@raprasad

**Comment by raprasad** [comment]
- [ ] finish up MetadataUpdate (rp)
- [ ] fix tests for editor
