### ISSUE TITLE
preprocess file: add "self" section

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#48]
- **preprocess_id** 
   - null if not saved to db; 
   - web gives an id; 
   - can also use hash
- description - link to github file
- timestamp - creation data
- schema version - see #50 
   - links to schema + documentation

**Comment by raprasad** [comment]
Needed for web:
 - get the PreprocessJob.id into the preprocess JSON under self->preprocess_id

Change points:
1. `preprocess_jobs/job_util.py` - send the "job.id" as an extra parameter here:
     - https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess_web/code/ravens_metadata_apps/preprocess_jobs/job_util.py#L25
     - e.g. ` task = preprocess_csv_file.delay(job.source_file.path, job_id=job.id)`
1. `preprocess_jobs/tasks.py`
    - update `preprocess_csv_file` to accept `**kwargs**`
    - if kwargs has a `job_id`, send it on to:
        - load_from_tabular_file
        - load_from_csv_file
1. `preprocess_runner.py`
    - `def load_from_tabular_file`
        - pass the existing `kwargs` onto `load_from_csv_file`
    - `load_from_csv_file`
        - check for a **job_id** in kwargs.  if it exists pass it on when creating PreprocessRunner
            - https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess/code/preprocess_runner.py#L124
1. `preprocess_runner.py` (still in same file)
    - Add a job_id attribute in the constructor:
         - https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess/code/preprocess_runner.py#L20
         - something like:  `self.job_id = kwargs.get('job_id', None)`
    - **Finally**, update `https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess/code/preprocess_runner.py#L176`
          - something like: `"preprocess_id": self.job_id

**Comment by kripanshu** [comment]
Implemented these steps

**Comment by raprasad** [comment]
For using **uuid**:

1. add it as a new attribute to the PreprocessJob model: 
    - https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess_web/code/ravens_metadata_apps/preprocess_jobs/models.py#L25
    - Note: after adding it, you'll have to use
         - `python manage.py makemigrations`
         - `python manage.p migrate`
1. Set the **uuid** by adding code between lines 68 and 69
1. At the end of this line, use `job_id=job.uuid)`:
    - https://github.com/TwoRavens/raven-metadata-service/blob/master/preprocess_web/code/ravens_metadata_apps/preprocess_jobs/job_util.py#L25

**Comment by raprasad** [comment]
kwargs note.  **kwargs in a function will return an empty dict `{}` if nothing is there.

So this:
```python
job_id = None
if kwargs is not None:
    job_id = kwargs.get('job_id')
```

can be replaced by:

```python
job_id = kwargs.get('job_id') 
# Note: this is the equivalent of: `job_id = kwargs.get('job_id', None)` 
```

**Comment by raprasad** [comment]
basic version is in...
