### ISSUE TITLE
view metadata detail page

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#71]
### page 1: list all PreprocessJob objects
   - url for HTML page: `/preprocess/list`
        - will be for the logged in user
        - but for now, just list everything

    - show list of all versions - use table https://getbootstrap.com/docs/4.0/content/tables/
        - include download button, this only downloads the latest version
             -  `JobUtil.get_latest_metadata()`  - opens file of latest version and returns an OrderedDict
---

## page 2: detail for a single PreprocessJob, includes MetadataUpdate objects

url for HTML page: `/preprocess/detail/<int:preprocess_id>`

- show list of all versions
   - original version: PreprocessJob
   - subsequent versions: MetadataUpate objects (if any, in chronological order)

## Info
   - ability to open/close each row
   - name, version number, size of file, date created, download button, view button

## view data button
   - show summary stats in a summary table
 

## If only one row found, e.g. original version
  - show the row already expanded

**Comment by kripanshu** [comment]
For size in FileField object django:
 - ``` Job = PreprocessJob.objects.all(); Job.size;``` no attribute named size
 - add to models.py? ``` file_size =models.FileField(\
                    help_text='Size of the file ',
                    upload_to='preprocess_file/%Y/%m/%d/',
                    blank=True)```
   - where are the attributes set? like created, name, source_file etc?
 - if I can set the attribute as a file size I can extract it from there.

For download button:
 - how to trigger the event for download?

**Comment by raprasad** [comment]
## versions page
- [ ] **editor/preview** -> viw editor (future)
   - consult with @tercer @vjdorazio; defer for now
- [ ] **download JSON** gets appropriate preprocess version
   - new api endpoint needed:  `/api/metadata/{preprocess id}/version/{ version number }`
   - why is url getting escaped (ok for now)
- [ ] **retrieve rows** button, add optional parameter for version number.  (this is a POST)
   - download button -> send version number to .js AJAX -> submits POST request

**Comment by raprasad** [comment]
Add to PreprocressJob and MetadataUpdate--with a new url for MetadataUpdate

```python
def get_download_preprocess_url(self):
        """Get the download url"""
        reverse('api_get_latest_metadata',
                kwargs=dict(preprocess_id=self.id))
```
